fix: Intermittent failure on start of `AccountCreationState`
hashgraph/hedera-local-node pull request #734
Opened 2024-08-14 12:59 UTC by victor-yanev

**Description**:

If the AccountCreationState begins, but the SDK is not yet connected to a healthy node, the local node would throw this error when starting up. We need to implement some sort of retry mechanism in case this issue happens.

This PR implements a retry mechanism to handle the scenario where the SDK is not connected to a healthy node at the start of the `AccountCreationState`. The retry mechanism will attempt to reconnect to a healthy node a specified number of times before failing.

**Changes:**
1. **Retry Mechanism:**
   - Added a new class `RetryUtils.ts` with a `retryTask` function to handle retry logic.
   - Configured the retry mechanism to execute the given task a specified number of times with a delay between attempts.

2. **Integration with `AccountCreationState`:**
   - Integrated the retry mechanism into the `AccountCreationState` to ensure it retries each call to the SDK for account creations

**Related issue(s)**:

Fixes #733

**Notes for reviewer**:

- The retry mechanism parameters (number of retries and delay) can be configured as needed.
- This change improves the robustness of the startup process by handling transient connection issues gracefully.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)
  - [x] Added unit tests in `RetryUtils.spec.ts` to verify the retry logic.
  - [x] Updated `AccountCreationState.spec.ts` to test the retry mechanism integration.

2024-08-15 06:48 UTC, natanasow approved these changes
LGTM

2024-08-19 13:34 UTC, natanasow approved these changes
LGTM

2024-08-19 13:36 UTC, georgi-l95 requested changes
Nice, small nit

2024-08-19 13:36 UTC, georgi-l95 commented on src/constants.ts
> +export const FAILED_TO_FIND_A_HEALTHY_NODE = "failed to find a healthy working node";
```suggestion
export const FAILED_TO_FIND_A_HEALTHY_NODE = "${CHECK_FAIL} failed to find a healthy working node";
```

2024-08-19 13:36 UTC, georgi-l95 commented on src/state/AccountCreationState.ts
> +        this.logger.warn(`Error occurred during task execution: "${error?.toString()}"`, this.stateName);
```suggestion
        this.logger.warn(`${CHECK_WARN} Error occurred during task execution: "${error?.toString()}"`, this.stateName);
```

2024-08-19 13:51 UTC, victor-yanev commented on src/state/AccountCreationState.ts
> +        this.logger.warn(`Error occurred during task execution: "${error?.toString()}"`, this.stateName);
discussed offline

2024-08-19 13:51 UTC, victor-yanev commented on src/constants.ts
> +export const FAILED_TO_FIND_A_HEALTHY_NODE = "failed to find a healthy working node";
discussed offline

2024-08-19 13:53 UTC, georgi-l95 approved these changes

2024-08-19 13:54 UTC, natanasow approved these changes

2024-08-19 13:55 UTC, merged